# Generated by Django 5.0.1 on 2024-02-01 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в длину от 3 до 11 символов и состоять только из цифр.', regex='^[0-9]{3,11}$')]),
        ),
    ]
